const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c={};c.window=c;vm.createContext(c);for(const f of ['credit-math','credit-lessons','credit-models','credit-ifrs','credit-content'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),c);
const M=c.CREDIT_MATH,L=c.CREDIT_LESSONS,near=(a,b,t=1e-8)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);
assert.equal(L.length,34);assert.equal(new Set(L.map(x=>x.id)).size,34);
const e=M.ecl({ead:100,pd:.1,lgd:.5,years:3,eir:0});near(e.one,5);near(e.life,5+4.5+4.05);near(e.cumulative,1-.9**3);near(M.sum(e.rows.map(x=>x.marginal)),e.cumulative);
near(M.ecl({ead:100,pd:.1,lgd:.5,years:1,eir:.1,lag:2}).one,5/1.1**3);near(M.ecl({pd:0}).life,0);near(M.ecl({lgd:0}).life,0);near(M.ecl({ead:0}).life,0);
for(const dep of [0,.5,1])for(const pd of [.005,.03,.2]){const r=M.distribution(100,pd,dep,100,.5,.99);near(M.sum(r.mass),1);near(M.sum(r.mass.map((v,k)=>v*k*r.unit)),100*pd*.5);assert(r.es+1e-8>=r.var);if(dep===0){near(r.corr,0);near(r.sd,100*.5*Math.sqrt(pd*(1-pd)/100));}}
const stage={origin:2,current:3,ratio:2,absolute:2,dpd:0,watch:'no',impaired:'no',rebut:'no'};
assert.equal(M.stage(stage).stage,1);assert.equal(M.stage({...stage,dpd:30}).stage,1);assert.equal(M.stage({...stage,dpd:31}).stage,2);assert.equal(M.stage({...stage,dpd:31,rebut:'yes'}).stage,1);assert.equal(M.stage({...stage,watch:'yes',rebut:'yes'}).stage,2);assert.equal(M.stage({...stage,dpd:90,rebut:'yes'}).stage,3);assert.equal(M.stage({...stage,current:6}).stage,2);assert.equal(M.stage({...stage,impaired:'yes'}).stage,3);
near(M.auc([.1,.2,.8,.9],[0,0,1,1]),1);near(M.auc([.5,.5,.5,.5],[0,0,1,1]),.5);assert.equal(M.DATA.length,720);assert.equal(M.DATA.filter(r=>r.late).length,240);assert(M.featureStats('duplicate').redundancy>.99);assert(M.model(['leak'],.05).testAuc>.99);
let count=0;for(const l of L){const d=Object.fromEntries(l.inputs.map(x=>[x.id,x.value])),cases=[d,...l.inputs.flatMap(x=>(x.options?x.options.map(y=>y[0]):[x.min,x.max]).map(v=>({...d,[x.id]:v}))),...['min','max'].map(edge=>Object.fromEntries(l.inputs.map(x=>[x.id,x.options?x.options[edge==='min'?0:x.options.length-1][0]:x[edge]])))];for(const s of cases){const r=l.compute(s);assert(!/NaN|Infinity|undefined/.test(JSON.stringify(r)),l.id);assert(r.explanation&&r.stats.length&&r.rows.length,l.id);for(const b of r.bars||[])assert(Number.isFinite(b.value),l.id);for(const series of r.series||[])for(const pt of series.data)assert(pt.every(Number.isFinite),l.id);count++;}assert.equal(c.LEARNING_CONTENT[l.id].questions.length,10,l.id);assert(c.LEARNING_CONTENT[l.id].questions.every(q=>q.length===2&&q[1].length>20),l.id);assert(l.sources.length&&l.scope.length>100,l.id);}
console.log(`PASS: ${count} scenarios; ECL benchmarks, default-distribution moments, SICR boundaries, model diagnostics; 34 concepts and 340 question-answer pairs.`);
