const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx={};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/regulation-data.js','utf8'),ctx);
const {sources,topics}=ctx.REGULATION_DATA;
assert.deepEqual(Object.keys(sources),['pra','us','basel']);assert.equal(topics.length,16);assert.equal(new Set(topics.map(t=>t.id)).size,16);
for(const topic of topics){assert(topic.name&&topic.question.endsWith('?')&&topic.keywords&&topic.group);for(const key of Object.keys(sources)){const e=topic.entries[key];assert(e&&e.ref&&e.page>0&&e.interpretation.length>55&&e.implication.length>45,topic.id+' '+key);assert(e.page<={pra:492,us:1241,basel:160}[key],topic.id+' '+key+' page');}}
const html=fs.readFileSync('dist/regulation.html','utf8');for(const asset of ['style.css','regulation.css','analytics.js','regulation-data.js','regulation.js'])assert(html.includes(asset)&&fs.existsSync('dist/'+asset));
for(const name of fs.readdirSync('dist').filter(x=>x.endsWith('.html'))){const page=fs.readFileSync('dist/'+name,'utf8');assert.equal((page.match(/href="regulation\.html"/g)||[]).length+(name==='regulation.html'?1:0)>0,true,name+' missing regulation navigation');assert(!/(Regulation navigator<\/a>){2}|(>Regulation<\/a>){2}/.test(page),name+' duplicate navigation');}
const {chromium}=require('/Users/vinaydutta/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://www.googletagmanager.com/**',r=>r.abort());await page.goto('http://localhost:8770/regulation.html',{waitUntil:'domcontentloaded'});
 assert.equal(await page.locator('#topic option').count(),16);assert.equal(await page.locator('#navigator-card .source-body section').count(),3);assert((await page.locator('#navigator-card').innerText()).includes('PRA'));
 await page.locator('#topic-search').fill('type A');assert.equal(await page.locator('#topic').inputValue(),'rfet');await page.locator('#jurisdiction').selectOption('us');assert((await page.locator('#navigator-card').innerText()).includes('type A'));
 await page.getByRole('tab',{name:'Comparator'}).click();assert.equal(await page.locator('.compare-card').count(),3);assert((await page.locator('#comparison-grid').innerText()).includes('Proposal'));
 await page.evaluate(()=>REGULATION_APP.select({topic:'indices',jurisdiction:'basel',mode:'navigator'}));assert.equal(await page.locator('#topic-name').innerText(),'Indices and multi-underlyings');
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const mode of ['navigator','comparator']){await page.evaluate(mode=>REGULATION_APP.select({topic:'data',mode}),mode);await page.waitForTimeout(50);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),mode+' overflow '+width);}}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>REGULATION_APP.select({topic:'rfet',jurisdiction:'us',mode:'comparator'}));await page.screenshot({path:'/private/tmp/quantsense-regulation/regulation-desktop.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 16 topics × 3 sources, references, search, navigator, comparator and responsive layouts.');})().catch(e=>{console.error(e);process.exit(1)});
